### ISSUE TITLE
Problems with launching on Astra Linux

### ISSUE THREAD

**Issue by pemelyanov** [AvaloniaDeveloperOrg/Avalonia.WebView#34]
When page that contains web view loads, application cause crash with error:

```
Gtk-WARNING **: Theme parsing error: gtk.css:3693:13: Not using units is deprecated. Assuming 'px'.
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.TypeInitializationException: The type initializer for 'WebKit.WebView' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WebKit.DeviceInfoPermissionRequest.get_GType()
   at GtkSharp.WebkitGtkSharp.ObjectManager.Initialize()
   --- End of inner exception stack trace ---
   at WebKit.WebView..ctor()
   at Linux.WebView.Core.LinuxApplication.<>c.<Linux.WebView.Core.ILinuxApplication.CreateWebView>b__23_0()
   at Linux.WebView.Core.LinuxDispatcher.<>c__DisplayClass7_0`1.<Linux.WebView.Core.ILinuxDispatcher.InvokeAsync>b__1(Object s, EventArgs e)
   at Gtk.Application.InvokeCB.Invoke()
   at GLib.Timeout.TimeoutProxy.Handler()
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Timeout.TimeoutProxy.Handler()
   at Linux.WebView.Core.LinuxApplication.<>c__DisplayClass19_0.<Linux.WebView.Core.ILinuxApplication.RunAsync>b__0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by soonssa** [comment]
I have encountered the same problem, do you have a solution?

**Comment by nicewillsuccess** [comment]
I also encountered this problem. Have you found a solution to it?
