### ISSUE TITLE
Avalonia.WebView not running on Linux Arm64 (Raspberry pi4)

### ISSUE THREAD

**Issue by Xrockyman** [AvaloniaDeveloperOrg/Avalonia.WebView#48]
Dear all, 

I've tried the sample project, and it runs fine on my Windows computer, but when I compile and run it on a raspberry it crashes because of a segmentation fault. In the library documentation, it is recommended that I perform the following installation on Linux:

sudo apt-get install libwebkit2gtk-4.0-37 

And I've installed the package with success, but the segmentation fault remains. 

error:
(WebViewSample.Desktop:2312): Gtk-CRITICAL **: 10:48:59.950: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
Segmentation fault

I've also debugged with GDB and also made a backtrace with it and here are the GDB relevant output: 

Thread 1 "WebViewSample.D" received signal SIGSEGV, Segmentation fault.
0x0000007ee5ee3f00 in hb_shape_plan_create_cached2 () from /lib/aarch64-linux-gnu/libharfbuzz.so.0
(gdb) bt
#0  0x0000007ee5ee3f00 in hb_shape_plan_create_cached2 () at /lib/aarch64-linux-gnu/libharfbuzz.so.0
#1  0x0000007ef0314e58 in hb_shape_full ()
    at /home/logger/Documents/DotnetTestes/Avalonia.WebView.Sample-main/Avalonia.WebView.Sample-main/Binary/net7.0/runtimes/linux-arm64/native/libHarfBuzzSharp.so
#2  0x0000007fba7bf844 in  ()
#3  0x0000007ff79d6370 in  () at /home/logger/dotnet/shared/Microsoft.NETCore.App/7.0.10/libcoreclr.so

I've also updated libharfbuzz libraries, but the problem persists. 

Thank you in advance for your help !

Best regards

**Comment by BhupiMAD** [comment]
@Xrockyman  Any luck running so far? I am in a similar situation. Need to run it on raspberry pi.

**Comment by Xrockyman** [comment]
@BhupiMAD, no luck I'm searching for alternatives but for now, nothing is working. If you find something first, please share :)

**Comment by charleypeng** [comment]
luckily, my Ubuntu arm64 on m1 mac(kvm) works fine m, and yes with some bugs but is working

**Comment by domenmerhar** [comment]
@charleypeng could you provide the exact version of Ubuntu?

**Comment by charleypeng** [comment]
> @charleypeng could you provide the exact version of Ubuntu?

22.04
