### ISSUE TITLE
Adapt to DotNet8 breaking changes.

### ISSUE THREAD

**Issue by zsh2401** [AvaloniaDeveloperOrg/Avalonia.WebView#64]
I am developing Avalonia 11.0.10 application with my computer that is macOS 14.5, arm64 m1 chip.

```C#
this.MainWebView.ExecuteJavaScriptAsync("alert('wow')")
```
I met a lot of errors:
```txt
The type WebKit.WKPreferences does not have a constructor that takes an ObjCRuntime.NativeHandle parameter but a constructor that takes an System.IntPtr parameter was found (and will be used instead). It's highly recommended to change the signature of the System.IntPtr constructor to be ObjCRuntime.NativeHandle.
The type WebKit.WKUserContentController does not have a constructor that takes an ObjCRuntime.NativeHandle parameter but a constructor that takes an System.IntPtr parameter was found (and will be used instead). It's highly recommended to change the signature of the System.IntPtr constructor.
...
```

All of this indicates to a Xamarain.Mac's incompatiblity with latest .net sdk.
There is a issue and related PR on upstream.
https://github.com/xamarin/xamarin-macios/issues/14046
https://github.com/xamarin/xamarin-macios/pull/14145

The code in Avalonia.WebView seems not up to date so this problem still.

There should be a fix so that we can use ExecuteJavaScriptAsync on MacOS arm64 Avalonia application.
It is important, right? 

Thanks!!

**Comment by KaranocaVe** [comment]
Same problem on .NET9.
`
Unhandled exception. System.TypeInitializationException: The type initializer for 'Builder.NativeImplementationBuilder' threw an exception.
  ---> System.Reflection.AmbiguousMatchException: Ambiguous match found for 'System.Runtime.InteropServices.Marshal IntPtr GetFunctionPointerForDelegateInternal(System.Delegate)'.
     at Builder.NativeImplementationBuilder..cctor()
     --- End of inner exception stack trace ---
     at Avalonia.WebView.MacCatalyst.ViewHandlerProvider..ctor()
     at AvaloniaExplorer.MainWindow..ctor()
     at AvaloniaExplorer.App.OnFrameworkInitializationCompleted()
     at AvaloniaExplorer.Program.Main(String[] args)
`
Already exist for one year.☹️
