### ISSUE TITLE
麒麟系统Desktop桌面Avalonia.WebView.Linux.ViewHandlerProvider

### ISSUE THREAD

**Issue by dingshuanglei** [AvaloniaDeveloperOrg/Avalonia.WebView#74]
`ing@ding-pc:~/linux-x64$ ./Ava.Client.Desktop
Unhandled exception. DryIoc.ContainerException: code: Error.UnableToSelectSinglePublicConstructorFromNone;
message: Unable to select a single public constructor from the implementation type 'Avalonia.WebView.Linux.ViewHandlerProvider' because the type does not have public constructors.
   at DryIoc.Throw.When(Boolean, Int32, Object , Object , Object , Object )
   at DryIoc.ReflectionFactory.ValidateAndNormalizeRegistration(Type, Object, Boolean, Rules, Boolean)
   at DryIoc.Container.Register(Factory, Type, Object, Nullable`1, Boolean)
   at DryIoc.Shared.Extensions.DryIocExtensions.RegisterSingleton(IRegistrator, Type, Type)
   at DryIoc.Shared.Extensions.DryIocExtensionsEx.RegisterSingleton[TFrom,TTo](IRegistrator )
   at Avalonia.WebView.Desktop.AppBuilderExtensions.<>c__DisplayClass0_0.<UseLinuxWebView>b__0(AppBuilder app)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ava.Client.Desktop.Program.Main(String[]) in D:\Ava.Client\Ava.Client\Ava.Client.Desktop\Program.cs:line 13
已放弃 (核心已转储)
ding@ding-pc:~/linux-x64$ sudo apt-get libwebkit2gtk-4-37
输入密码
E: 无效的操作 libwebkit2gtk-4-37
ding@ding-pc:~/linux-x64$ 
`

**Comment by dingshuanglei** [comment]
`ding@ding-pc:~/linux-x64$ sudo apt-get install libwebkit2gtk-4.0-37
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列软件包是自动安装的并且现在不需要了：
  archdetect-deb atril-common dmeventd fonts-mathjax libaio1 libatrildocument3 libdebian-installer4 libdevmapper-event1.02.1 libdjvulibre-text libdjvulibre21 libgxps2
  libjs-mathjax libkpathsea6 liblvm2cmd2.03 libspectre1 libsynctex2 localechooser-data lvm2 user-setup
使用'sudo apt autoremove'来卸载它(它们)。
推荐安装：
  gstreamer1.0-gl
下列【新】软件包将被安装：
  libwebkit2gtk-4.0-37
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 457 个软件包未被升级。
需要下载 0 B/17.8 MB 的归档。
解压缩后会消耗 68.7 MB 的额外空间。
正在选中未选择的软件包 libwebkit2gtk-4.0-37:amd64。
(正在读取数据库 ... 系统当前共安装有 198135 个文件和目录。)
准备解压 .../libwebkit2gtk-4.0-37_2.38.6-0kylin0.20.04.1k0.2_amd64.deb  ...
正在解压 libwebkit2gtk-4.0-37:amd64 (2.38.6-0kylin0.20.04.1k0.2) ...
正在设置 libwebkit2gtk-4.0-37:amd64 (2.38.6-0kylin0.20.04.1k0.2) ...
正在处理用于 libc-bin (2.31-0kylin9.2) 的触发器 ...
ding@ding-pc:~/linux-x64$ ./Ava.Client.Desktop
Unhandled exception. DryIoc.ContainerException: code: Error.UnableToSelectSinglePublicConstructorFromNone;
message: Unable to select a single public constructor from the implementation type 'Avalonia.WebView.Linux.ViewHandlerProvider' because the type does not have public constructors.
   at DryIoc.Throw.When(Boolean, Int32, Object , Object , Object , Object )
   at DryIoc.ReflectionFactory.ValidateAndNormalizeRegistration(Type, Object, Boolean, Rules, Boolean)
   at DryIoc.Container.Register(Factory, Type, Object, Nullable`1, Boolean)
   at DryIoc.Shared.Extensions.DryIocExtensions.RegisterSingleton(IRegistrator, Type, Type)
   at DryIoc.Shared.Extensions.DryIocExtensionsEx.RegisterSingleton[TFrom,TTo](IRegistrator )
   at Avalonia.WebView.Desktop.AppBuilderExtensions.<>c__DisplayClass0_0.<UseLinuxWebView>b__0(AppBuilder app)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ava.Client.Desktop.Program.Main(String[]) in D:\Ava.Client\Ava.Client\Ava.Client.Desktop\Program.cs:line 13
已放弃 (核心已转储)
`
